### PR TITLE
Refactor codebase to use common C#/U# conventions  

### PR DESCRIPTION
**Pull request by FairlySadPanda**
This PR refactors the codebase to read like regular C# rather than C. It follows the following rules:

1. Consts are stored at the top of the class.
2. Vars are stored below Consts.
3. Subscription events (Start, Update...) are stored below Consts.
4. Public methods are stored below Subscriptions.
5. Private methods are stored below Public methods.
6. CONSTS_ARE_DEFINED_WITH_SCREAMING_SNAKE_CASE
7. varsAreDefinedWithSnakeCase
8. MethodsAreDefinedWithPascalCase
9. Best effort is made to avoid Hungarian naming (public Material ballMaterial -> public Material ball)

Some effort has also been made to rip out repetitiveGetComponent calls, properly error and fail if GetComponent returns null, and remove unneeded ifdefs and debug logging.
 
This is a major refactor and is likely to have problematic changes and as such needs thorough testing before it is applied to the codebase.

### CODE REVIEW

**Comment by FairlySadPanda** [comment]
THIS IS A BROKEN PR AT THE MOMENT but it's 2AM.

The prefab will need re-assembling as many of the references have fallen off.

The prefab will also need a lot of testing - there's absolutely going to be wonky code due to changes made whilst cleaning up the codebase.

**Comment by Terri00** [comment]
Udon convention specifies methods should be prefixed with _

**Comment by FairlySadPanda** [comment]
> Udon convention specifies methods should be prefixed with _ to prevent them being run over the network by modded clients.
> 
> also, the orignal code doesn't read like C, at all.

No, it reads like a Gorilla wrote it on speed. I was being polite.

**Comment by Terri00** [comment]
This 'style' refactor is superficial and pointless, it just breaks stuff, completely destroys diffs, and makes things more confusing.

Variables used in networking were prefixed with sn_ for a reason.
Constants were prefixed with k_ for a reason. 
Events called by external sources were prefixed with tr_ for a reason.
Menu calls were prefixed with m_ for a reason.
Desktop stuff were prefixed with dk_ for a reason.

**Comment by FairlySadPanda** [comment]
I would encourage you to read the following documentation on C# code conventions:

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions
https://google.github.io/styleguide/csharp-style.html (I personally dislike the Google style, but it's a cohesive style, although thanks to the _ role in U# we would need to ignore its rule about _ ahead of private components of a class)
https://github.com/raywenderlich/c-sharp-style-guide
https://blog.submain.com/coding-standards-c-developers-need/

There are others.

**Comment by Terri00** [comment]
Why do you care about these?

**Comment by FairlySadPanda** [comment]
Harry, you should care about these because code conventions, especially ones that follow language examples and match with support threads on places like StackOverflow, and U# code written for the Prefabs database and elsewhere, are easier to understand, extend and refactor.

This is a popular prefab and others other than yourself should be able to understand it when they want to modify it.

**Comment by Terri00** [comment]
My point is you've only made it more confusing, especially for people who are actually writing the systems

Your refactor may be compliant to some random convention you found, but your changes are at the detriment of actually understanding the systems.

**Comment by FairlySadPanda** [comment]
Harry, the first one I linked is from the *maintainers of C#*

**Comment by Terri00** [comment]
**Your PR does not make it any easier to understand the code**

**Comment by Terri00** [comment]
Please tell me how renaming `sn_packetid` to `clock` makes any fucking sense.

**Comment by FairlySadPanda** [comment]
Please stop swearing - there's enough of that in your comments on the codebase already.

**Comment by Terri00** [comment]
Sorry squire

**Comment by FairlySadPanda** [comment]
I would advice you to read up on networking terminology. You can see an example of "clock" as a term in networking in UdonStringEvents. https://en.wikipedia.org/wiki/Vector_clock

**Comment by Terri00** [comment]
Packet ID is way more obvious than clock at describing what it is.

**Comment by Terri00** [comment]
does `clock` refer to cpu current clock cycles? does it refer to the time? does it refer to the physics timestep?

**Comment by FairlySadPanda** [comment]
If you'd like to call out specific names as unclear, you should be able to use Github to comment in-line whilst doing a review (I'm used to doing this on internal projects - I think regular Github also has this feature). I can then action each point as separate commits.

This would also give you the opportunity to spot any functional breakages.

**Comment by Terri00** [comment]
It's just a poor PR, sorry.

**Comment by FairlySadPanda** [comment]
@Xiexe My intent is to clean up work I've got left over then take an hour to salvage the prefab.

**Comment by Terri00** [comment]
One more note, I noticed you replaced `[SerializeField]` on private members of the script.

Due to the way udon works, `[SerializeField]` should be used in place of `public` to mark a variable as settable in the inspector.
Using the public will flag means the compiler will set it as 'export', which slows down indexes from other scripts as the Udon VM fetches them by string.

**Comment by FairlySadPanda** [comment]
That's fine:- I'll address performance separately.

If public as a property has this issue, this sounds more like a U# problem than a Udon problem. I'll message him about it.

Closing this as Xiexe has signalled they're unlikely to be continuing as an active maintainer. I will continue work on my own repo alongside Prefabbers who are interested.

**Comment by Terri00** [comment]
I'm curious why you changed it in the first place? Those members don't need to be accessed from anywhere else, so why make them public?

It's not a Udon problem or a U# problem, its just how its designed and is honestly very logical.

**Comment by FairlySadPanda** [comment]
That one is 100% personal preference and I may well refactor it back to using SerializeField. Generally w/ this sort of refactor I'll go to the nth degree in one direction as an exploration. It can take a couple of minutes to flip one way or the other, which by refactor standards is not especially long.

In this case there is no performance differential in U# between them, having checked with Merlin just now. 

If they go back to being [SerializeField] it'll be demarking them as private anyway just to keep everying lined up well.

**Comment by Terri00** [comment]
I can confirm through testing that there is a performance difference, albeit a very small one.

A program with more exports obviously has to take SOME amount more to search through to find the correct one, right?

**Pull request closed without merging**
